# Generated by Django 5.2.7 on 2025-10-21 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=50)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('available_copies', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_copies', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('isbn', None), _negated=True), fields=('isbn',), name='unique_isbn_not_null')],
            },
        ),
    ]
