# Generated by Django 5.2.7 on 2025-10-26 14:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('category', models.CharField(blank=True, default='General', max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=50)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('available_copies', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_copies', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('isDeleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_created', to=settings.AUTH_USER_MODEL, to_field='user_id')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_deleted', to=settings.AUTH_USER_MODEL, to_field='user_id')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_updated', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('isbn', None), _negated=True), fields=('isbn',), name='unique_isbn_not_null')],
            },
        ),
    ]
